### PR TITLE
ci: track overrides for purchase, stock and manufacturing cycles (v15)

### PR DESCRIPTION
**Pull request by Alchez**

### CODE REVIEW

**Comment by Alchez** [comment]
@agritheory A couple functions had additions between v14 and v15 that I've added into this PR, but I'm not sure if they should stay out. Let me know.

**Review by agritheory — APPROVED** [review]

**Comment by agritheory** [comment]
@Alchez I think it's correct to include them. One of them needs a re-review and there's an issue with the pytest action on all the cherry-picked commits that we need to resolve.

**Comment by HKuz** [comment]
Thanks for doing this @Alchez - the purchase cycle commits all looked good 👍

**Comment by Alchez** [comment]
> there's an issue with the pytest action on all the cherry-picked commits that we need to resolve.

@agritheory seems like an issue where the tests expect the job cards to be submitted, but the test setup isn't setting it up. Not sure if this is a v15 issue, but I can look into it.

**Update**: version-14 used to create `time_logs` for Job Cards, but they've since [separated scheduled time from actual time](https://github.com/frappe/erpnext/pull/35921).

**Review by agritheory — APPROVED** [review]

**Review by agritheory — APPROVED** [review]

**Comment by agritheory** [comment]
@fproldan It appears I am not using the track overrides feature correctly, can you offer some guidance. These a lot of extra noise in this PR, trying to get all the pre-commit processes to work.

**Pull request merged**
