### PR TITLE
Alternative workstation in job card and operation

### PR DESCRIPTION
**Pull request by viralkansodiya**
#41 
on validate hooks event of job card if operation is selected, alternative workstation will fetch automatically

frappe has not allowed to add table multiselect field in child table
if you add a table multiselect type field to the child table, the user will not be able to open a row of that child table.

error as mentioned below image
bom

### CODE REVIEW

**Comment by viralkansodiya** [comment]
@agritheory 
Final changes has been done from my side
Please watch this video first

https://www.awesomescreenshot.com/video/24855534?key=25bfb279c8d065cb1f8439b09812b27f

**Comment by viralkansodiya** [comment]
@agritheory 
in test cases, which workstation we have to set in alternative workstation.
can we assign some random workstation in operation alternative workstation?

**Comment by agritheory** [comment]
@viralkansodiya I don't think "random" is a good idea, but I think it'll be good to set up the alternative workstations in `[tests/fixtures.py](https://github.com/agritheory/inventory_tools/blob/version-14/inventory_tools/tests/fixtures.py#L60)` and `[tests/setup.py](https://github.com/agritheory/inventory_tools/blob/version-14/inventory_tools/tests/setup.py#L186)`. We don't need it for all workstations, but one or two to be able to create a test or two and configure it would be good.

**Comment by viralkansodiya** [comment]
@agritheory Thanks for update

I will update that soon

**Comment by viralkansodiya** [comment]
@agritheory 
Currently, we don't have any alternative workstations.
at the time of installation, can we create some new alternative workstations?
for an example:
Workstations: Cooling Racks Station
Alternative Workstations:  Cooling Racks Station-1 , Cooling Racks Station-2 , Cooling Racks Station-3

I believe that the other workstations currently listed may not be suitable as alternative workstations.

**Comment by viralkansodiya** [comment]
Closing this PR and raise new because of some un resolved conflict

**Pull request closed without merging**
