### PR TITLE
[v2] Aggregate and/or Split Quotations into multiple Sales Orders

### PR DESCRIPTION
**Pull request by fproldan**
https://github.com/agritheory/inventory_tools/issues/55

### CODE REVIEW

**Comment by agritheory** [comment]
@fproldan The Material Demand refactor doesn't respect the selected Price List:

image


image

**Comment by fproldan** [comment]
> @fproldan The Material Demand refactor doesn't respect the selected Price List:
> 
> image
> 
> image

@agritheory  There was a variable name collision

**Comment by agritheory** [comment]
image


To make this compatible with a multi-company workflow, we need to follow the same pattern as is used on the Purchase Order. That means a custom field that marks the Sales Order as multi-company and an override for `validate_with_previous_doc` [like this](https://github.com/agritheory/inventory_tools/blob/version-14/inventory_tools/inventory_tools/overrides/purchase_order.py#L26-L54)

There may be downstream overrides that are required in the Sales Invoice and Delivery Note. Executing this workflow should be inside the scope of the tests for this feature.

**Comment by agritheory** [comment]
@fproldan Let's rebase and refresh this after the issues with #64 are sorted out

**Pull request closed without merging**
