### PR TITLE
Manufacturing Over/Under Production

### PR DESCRIPTION
**Pull request by fproldan**
#40

### CODE REVIEW

**Comment by fproldan** [comment]
@HKuz  This is ready for review, thanks!

**Comment by HKuz** [comment]
This looks great, @fproldan ! Only thing I uncovered was the last test `test_validate_job_card` was failing locally for me. It wasn't a code issue (the feature is doing what it should) - I had the same (user) error in the UI. It's complaining because there was already a submitted job card for the production qty that the test data automatically completes. I made the following edits to the test and it's passing. I didn't want to push up these changes in case you weren't having the issues on your end:


```py
def test_validate_job_card():
	work_order = frappe.get_doc("Work Order", {"item_name": "Ambrosia Pie"})
	jc = frappe.get_doc("Job Card", {"work_order": work_order.name, "operation": work_order.operations[0].operation})
	jc.cancel()
	job_card = create_job_card(work_order, work_order.operations[0].as_dict(), auto_create=True)
	job_card.append(
		"time_logs",
		{
			"from_time": now(),
			"to_time": now(),
			"completed_qty": work_order.qty,
		},
	)
	job_card.save()
	assert job_card.validate_job_card() == None

	overproduction_percentage_for_work_order = frappe.db.get_value(
		"BOM", work_order.bom_no, "overproduction_percentage_for_work_order"
	)
	over_production_qty = work_order.qty * (1 + overproduction_percentage_for_work_order / 100)
	job_card.time_logs[0].completed_qty = over_production_qty
	job_card.save()

	assert job_card.validate_job_card() == None

	job_card.time_logs[0].completed_qty = over_production_qty + 10
	job_card.save()

	with pytest.raises(ValidationError) as exc_info:
		job_card.validate_job_card()

	assert (
		f"The <strong>Total Completed Qty</strong> (<strong>{over_production_qty + 10}</strong>) must be equal to <strong>Qty to Manufacture</strong> (<strong>{job_card.for_quantity}</strong>)"
		in exc_info.value.args[0]
	)

```

**Comment by fproldan** [comment]
@fproldan Thanks! 
For me both your solution and the original worked, only have to change the assertion (without the <strong>)

Let me know if is passing now.

**Comment by fproldan** [comment]
@HKuz  Thanks! 
For me both your solution and the original worked, only have to change the assertion (without the <strong>)

Let me know if is passing now.

**Comment by HKuz** [comment]
@fproldan  - I think it was a version issue. I updated my ERPNext and Frappe apps locally and I no longer get the error when there's already a completed Job Card in place for a work order. (It still wants those strong tags, though? If it's passing in CI should be fine but we can always do a replace to remove the tags before we compare strings if it causes a problem).

**Review by HKuz — APPROVED** [review]

**Pull request merged**
