### PR TITLE
ci: track overrides for stock and manufacturing cycles

### LINKED ISSUE #88: Track overrides with GHA Helper (Stock and Manufacturing modules)
@fproldan Has built a GHA to help with tracking overrides based on commit history: https://github.com/diamorafaela/track-overrides

This ticket  is for the Stock Module (Stock Entry, Stock Reconciliation, Job Card, Production Plan, Operation)

### PR DESCRIPTION
**Pull request by Alchez**
Closes #88.

### CODE REVIEW

**Review by fproldan — APPROVED** [review]

**Review by agritheory — APPROVED** [review]

**Review by HKuz — APPROVED** [review]

**Comment by agritheory** [comment]
@Alchez Can you raise this against version-15 branch also.

**Comment by Alchez** [comment]
@agritheory should I create a single PR that merges all the changes from v14 -> v15? Or do you want to review these individually?

**Comment by agritheory** [comment]
Good question. One that raises the overrides helpers and one that collects all the other V15 features we should backport. Alternatively we should set up automated backports. I think tracking overrides should not be backported because the commit hash should definitely be different.

**Comment by Alchez** [comment]
@agritheory Yeah, makes sense. I can setup the PRs tomorrow.

**Comment by Alchez** [comment]
@agritheory @HKuz 

I've added some port PRs, please have a look:
- (All Override Docs) #91
- (Inventory Tool Settings in Boot) #92
- (Alternative Workstation) #93

**Pull request merged**
